// Generated by scripts/art/make.mjs. Files live in web/public/art.
export const AVATARS = [{"id":"sprout","name":"Sprout"},{"id":"mochi","name":"Mochi"},{"id":"hop","name":"Hop"},{"id":"pip","name":"Pip"},{"id":"bo","name":"Bo"},{"id":"lulu","name":"Lulu"},{"id":"ribbit","name":"Ribbit"},{"id":"kit","name":"Kit"},{"id":"hoot","name":"Hoot"},{"id":"boo","name":"Boo"},{"id":"bolt","name":"Bolt"},{"id":"zib","name":"Zib"}];
export const EMOJI = [{"id":"love","name":"love"},{"id":"lol","name":"lol"},{"id":"hype","name":"hype"},{"id":"omw","name":"omw"},{"id":"braai","name":"braai"},{"id":"cheers","name":"cheers"},{"id":"free","name":"free"},{"id":"meh","name":"meh"},{"id":"sleepy","name":"sleepy"},{"id":"party","name":"party"}];
export const STICKERS = [{"id":"letsgo","label":"Let's go!"},{"id":"omw","label":"On my way"},{"id":"braai","label":"Braai?"},{"id":"missyou","label":"Miss you"},{"id":"yes","label":"Yes!!"},{"id":"nah","label":"Nah"},{"id":"approved","label":"Planner approved"},{"id":"weekend","label":"Weekend mode"},{"id":"callme","label":"Call me"},{"id":"thanks","label":"Thank you"}];
export const GIFS = [{"id":"wave","label":"Hi!"},{"id":"dance","label":"Dance"},{"id":"love","label":"Love you"},{"id":"yay","label":"Yay!"},{"id":"lol","label":"LOL"},{"id":"omw","label":"On my way"},{"id":"hype","label":"Hype"},{"id":"planning","label":"Planning…"},{"id":"yes","label":"Yes!"},{"id":"zzz","label":"Sleepy"}];
export const avatarUrl = (id) => `/art/avatars/${id}.svg`;
export const emojiUrl = (id) => `/art/emoji/${id}.svg`;
export const stickerUrl = (id) => `/art/stickers/${id}.svg`;
export const gifUrl = (id) => `/art/gifs/${id}.gif`;
export const EMOJI_IDS = new Set(EMOJI.map((e) => e.id));
