// Draws the whole art set into web/public/art and writes the list the app reads (web/src/lib/art.js).
//   node scripts/art/make.mjs            (needs the root devDependencies: playwright, gifenc)
// SVGs are written as-is; GIF frames and PNG avatars (for notification icons) are rasterised in Chromium.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import gifenc from 'gifenc';
const { GIFEncoder, quantize, applyPalette } = gifenc;
import { AVATARS, EMOJI, STICKERS, GIFS, SCENES } from './sets.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const OUT = path.join(ROOT, 'web/public/art');
const write = (rel, data) => { const f = path.join(OUT, rel); fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, data); };

for (const a of AVATARS) write(`avatars/${a.id}.svg`, a.svg());
for (const e of EMOJI) write(`emoji/${e.id}.svg`, e.svg());
for (const s of STICKERS) write(`stickers/${s.id}.svg`, s.svg());
for (const s of SCENES) write(`scenes/${s.id}.svg`, s.svg());

const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
const page = await browser.newPage();
await page.setContent('<html><body></body></html>');

/** SVG strings -> RGBA frames (base64), drawn at w x h. */
const raster = (svgs, w, h) => page.evaluate(async ({ svgs, w, h }) => {
  const out = [];
  for (const s of svgs) {
    const img = new Image();
    img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(s);
    await img.decode();
    const c = new OffscreenCanvas(w, h);
    const g = c.getContext('2d');
    g.drawImage(img, 0, 0, w, h);
    const d = g.getImageData(0, 0, w, h).data;
    let bin = '';
    for (let i = 0; i < d.length; i += 0x8000) bin += String.fromCharCode.apply(null, d.subarray(i, i + 0x8000));
    out.push(btoa(bin));
  }
  return out;
}, { svgs, w, h });

const png = (svgStr, size) => page.evaluate(async ({ s, size }) => {
  const img = new Image();
  img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(s);
  await img.decode();
  const c = new OffscreenCanvas(size, size);
  c.getContext('2d').drawImage(img, 0, 0, size, size);
  const b = new Uint8Array(await (await c.convertToBlob({ type: 'image/png' })).arrayBuffer());
  let bin = '';
  for (let i = 0; i < b.length; i += 0x8000) bin += String.fromCharCode.apply(null, b.subarray(i, i + 0x8000));
  return btoa(bin);
}, { s: svgStr, size });

// Notification icons can't be SVG on every phone, so avatars also get a 192px PNG.
for (const a of AVATARS) write(`avatars/${a.id}.png`, Buffer.from(await png(a.svg(), 192), 'base64'));

const SIZE = 240; // 1.5x the 160px they're shown at
for (const g of GIFS) {
  const svgs = Array.from({ length: g.frames }, (_, i) => g.frame(i / g.frames));
  const frames = await raster(svgs, SIZE, SIZE);
  const enc = GIFEncoder();
  frames.forEach((b64, i) => {
    const rgba = new Uint8Array(Buffer.from(b64, 'base64'));
    const palette = quantize(rgba, 256);
    enc.writeFrame(applyPalette(rgba, palette), SIZE, SIZE, { palette, delay: g.delay, repeat: 0 });
  });
  enc.finish();
  write(`gifs/${g.id}.gif`, Buffer.from(enc.bytes()));
  if (process.env.PREVIEW) write(`gifs/${g.id}-first.svg`, svgs[0]);
}
await browser.close();

const list = (items, fields) => JSON.stringify(items.map((x) => Object.fromEntries(fields.map((f) => [f, x[f]]))));
fs.writeFileSync(path.join(ROOT, 'web/src/lib/art.js'), `// Generated by scripts/art/make.mjs. Files live in web/public/art.
export const AVATARS = ${list(AVATARS, ['id', 'name'])};
export const EMOJI = ${list(EMOJI, ['id', 'name'])};
export const STICKERS = ${list(STICKERS, ['id', 'label'])};
export const GIFS = ${list(GIFS, ['id', 'label'])};
export const avatarUrl = (id) => \`/art/avatars/\${id}.svg\`;
export const emojiUrl = (id) => \`/art/emoji/\${id}.svg\`;
export const stickerUrl = (id) => \`/art/stickers/\${id}.svg\`;
export const gifUrl = (id) => \`/art/gifs/\${id}.gif\`;
export const sceneUrl = (id) => \`/art/scenes/\${id}.svg\`;
export const EMOJI_IDS = new Set(EMOJI.map((e) => e.id));
`);
const size = (d) => fs.readdirSync(path.join(OUT, d)).reduce((n, f) => n + fs.statSync(path.join(OUT, d, f)).size, 0);
console.log(`art: ${AVATARS.length} avatars, ${EMOJI.length} emoji, ${STICKERS.length} stickers, ${GIFS.length} GIFs, ${SCENES.length} scenes`,
  `(${['avatars', 'emoji', 'stickers', 'gifs', 'scenes'].map((d) => `${d} ${Math.round(size(d) / 1024)}KB`).join(', ')})`);
